### ISSUE TITLE
Training with BB3TXTLoss

### ISSUE THREAD

**Issue by libornovax** [libornovax/master_thesis_code#26]
I carried one test on 20170318 with the same network as was used for 2D bounding boxes, but the performance was poor. Thus I decided to make some changes - enlarge the network.

This is the **second part** of the training curve:
![learning_curves2](https://cloud.githubusercontent.com/assets/19144779/24144555/fb742b22-0e2d-11e7-9016-b49d63897d55.png)

**Comment by jeannotes** [comment]
hi, for 100000iterations, how much time does it cost? @libornovax

**Comment by libornovax** [comment]
@jeannotes depends on your GPU. I think for me it was about 3 days on Tesla K40
