### ISSUE TITLE
NMS!!

### ISSUE THREAD

**Issue by libornovax** [libornovax/master_thesis_code#31]
Merging is too slow and I don't think that the classical NMS can really use the potential of the detector...

**Comment by ansabsheikh9** [comment]
Hello Mr. Novak,
great work,
Could you tell me how are you performing NMS on oriented 3D boxes?
BR,
Ansa

**Comment by libornovax** [comment]
Hi, I chose perhaps the simplest solution - project the 3D boxes on the ground plane, create axis-aligned 2D bounding boxes on the ground plane (as an approximation of the oriented ones) and then perform classical NMS on them. Hope that helps.

**Comment by ansabsheikh9** [comment]
Thank you for your reply. 👍 
Best Regards,
Ansab
