### ISSUE TITLE
Dataset - ground truth enhancement for unsure coordinates

### ISSUE THREAD

**Issue by libornovax** [libornovax/master_thesis_code#32]
Training
--------
Now I am always learning all 4 (7) coordinates of the bounding box. But when a part of a car is outside of the image or occluded we are not sure about where the boundary of the bounding box is:
<img width="610" alt="screen shot 2017-04-04 at 11 38 53 am" src="https://cloud.githubusercontent.com/assets/19144779/24650709/51982b22-192b-11e7-9772-08d1f672d1c6.png">

In this case we should not force the network to compute gradients on the `ymin` coordinate because we do not even know precisely where it is. Thus we should zero out the gradient from this coordinate. This is essentially learning on datasets with incomplete data!

In order to do this we need to annotate the "unsure" bounding box coordinates. The unsure coordinates are either outside of the image or caused by occlusion of the cars.

Testing
-------
In testing we also should change the way we compute intersection over union of the detections with ground truth boxes - only compute IOU on the part, where we are sure about the object. That is crop the detected bounding box on the "unsure" coordinate from ground truth and then compute the IOU.

![img_2785](https://cloud.githubusercontent.com/assets/19144779/24651130/eeb9acea-192c-11e7-8bef-0f6e675bfef0.jpg)

**Comment by wangyarui** [comment]
Please，could you tell how to get  this file "**macc_0.3_r2_x2_to_x16_s2_iter_40000.caffemodel** ",and I could not find it in all folders.

**Comment by libornovax** [comment]
There is a link to dropbox in the readme:
https://www.dropbox.com/s/zt39813k90rkswo/macc_0.3_r2_x2_to_x16_s2_iter_40000.caffemodel?dl=0 <https://www.dropbox.com/s/zt39813k90rkswo/macc_0.3_r2_x2_to_x16_s2_iter_40000.caffemodel?dl=0>
