### ISSUE TITLE
improper result

### ISSUE THREAD

**Issue by vishnureghu007** [libornovax/master_thesis_code#40]
i tried your network by finding the projection matrix from camera parameters which is used for the input image.
CalibExtrParameters.VP_X=315;
CalibExtrParameters.VP_Y=180;
CalibExtrParameters.flPitch=0.08447394f;
CalibExtrParameters.intCameraHeight_mm=1.400000f;
CalibExtrParameters.flYaw=0.000000;
CalibExtrParameters.flRoll=0.000000;
CalibExtrParameters.intCameraLateralOffset_mm=0;
CalibExtrParameters.intLowestRowDistance_mm=0;
CalibIntParameters.u16SensorRows=480;
CalibIntParameters.u16SensorColumns=640;
CalibIntParameters.flLensFocalLength=5.940000;
CalibIntParameters.flSensorPixelHeight=(float32_t)(0.003750 );
CalibIntParameters.flSensorPixelWidth=(float32_t)(0.003750 );
CalibIntParameters.flHorizontalFOV=0;
CalibIntParameters.flSensorHeight=0;
CalibIntParameters.flVerticalFOV=0;

input image is resized to half inorder to avoid GPU RAM overflow. 
(adjusted the camera parameters for the resized condition)
![screenshot from 2017-06-27 09-23-42](https://user-images.githubusercontent.com/15410424/27570456-ed0fa274-5b1b-11e7-9f66-c21a492f48da.png)

i found the bounding box localization when car is at some orientation is not proper and some points being shifted.what might be the reason for this?
is it because of the ground plane eqn which i used.

**Comment by vishnureghu007** [comment]
updated question

**Comment by libornovax** [comment]
It seems to me that it is more of a problem with the vantage point of the camera. The detector is trained only on KITTI, where the camera is mounted higher and thus it might expect the cars to be in a slightly different position. Can you share the image that you used for detection without the annotation? and the P and ground plane? I will try to do some further analysis...

**Comment by vishnureghu007** [comment]
![0](https://user-images.githubusercontent.com/15410424/27587423-02ba565a-5b62-11e7-86a6-9de24431c456.png)
Attached different image Which shows same problem
p=[775.895121 ,0.000000 ,223.734243 ,0.000000 ,-7.590384 ,792.000000 ,89.679351 ,0.000000 ,-0.084338 ,0.000000 ,0.996437 ,0.000000 ]
g=g2=['0.000000','1.000000','0.00000','-2.00000']

**Comment by libornovax** [comment]
So I found out that your camera is looking more down (you can see it on the top view that all the circled cars were reconstructing some 25m in front of the ego vehicle, which is obviously not the case in the image - some of them are above the horizon and should be ignored)
![screen shot 2017-06-27 at 5 13 26 pm](https://user-images.githubusercontent.com/19144779/27595141-1fc13f44-5b5c-11e7-817d-3074bde926bd.png)
so I changed the ground plane equation to:
0.000000 1.000000 -0.070000 -2.00000

The result looks a bit better (you can play around a bit with the pitch):
![screen shot 2017-06-27 at 5 12 25 pm](https://user-images.githubusercontent.com/19144779/27595459-0860e254-5b5d-11e7-8af0-01bfbf70c79e.png)

Another thing is that the network was not trained to detect vans so in this case you can see that the confidence of the detections is not very high, it usually is about 0.75 and more for good detections.

**Comment by vishnureghu007** [comment]
Thanks Libor. I will try the same.
