### ISSUE TITLE
Multi-class training 

### ISSUE THREAD

**Issue by ranjithrajasimha** [libornovax/master_thesis_code#41]
To train a multi class detector, I tried changing **num_output** from **5** to **6** in last 4 layers in train_val.prototxt, but it is throwing error. Can this model be used for detecting multi-classes, If it is compatible for multi-class, Do I need to make any other modifications to train?

**Comment by libornovax** [comment]
Hi, the model is in theory capable of doing multiclass detection, however there is no support for it in the code. One would have to update all of the custom layers (data reading and loss computation) to support multiple classes and correct loss computation - also adding softmax for the class output.

**Comment by ranjithrajasimha** [comment]
Oh okay. Thank you, Libor.

**Comment by suvam-bag** [comment]
Hi @libornovax,

I am trying to convert the network into a multiclass network. However I am not sure, if this can be done using the current data layer, as most caffe tutorials suggest either to use "HDF5" or "LMDB" as backend. Do you have any suggestion on this?
