### ISSUE TITLE
caffe make  run error

### ISSUE THREAD

**Issue by zgq91** [libornovax/master_thesis_code#46]
Hi:
   When I execute the make command in caffe, the following error occurs:
  /include/caffe/layers/bb3txt_loss_layer.hpp:109:5: error: 'shared_ptr' in namespace 'std' does not name a type
     std::shared_ptr<Blob<Dtype>> _accumulator;
     ^
./include/caffe/layers/bb3txt_loss_layer.hpp:121:5: error: 'shared_ptr' in namespace 'std' does not name a type
     std::shared_ptr<Blob<Dtype>> _diff;

src/caffe/layers/bb3txt_loss_layer.cpp:236:30: error: expected primary-expression before ',' token
     CHECK((std::is_same<Dtype,float>::value)) << "BB3TXTLossLayer supports only float!";
                              ^
src/caffe/layers/bb3txt_loss_layer.cpp:236:31: error: expected primary-expression before 'float'
     CHECK((std::is_same<Dtype,float>::value)) << "BB3TXTLossLayer supports only float!";
                               ^
src/caffe/layers/bb3txt_loss_layer.cpp:236:31: error: expected ')' before 'float'
src/caffe/layers/bb3txt_loss_layer.cpp:236:88: error: expected ')' before ';' token
     CHECK((std::is_same<Dtype,float>::value)) << "BB3TXTLossLayer supports only float!";

my environment：ubuntu14.04  cuda8.0+cudnn5.1 anaconda2

**Comment by libornovax** [comment]
Hi, you should use CMake and make to build the project. Go to the caffe folder and create a directory 'build' then run 

cd build
cmake ..
make

The error you are getting comes from c++11

**Comment by zgq91** [comment]
@libornovax  my g++ 4.8 ，How to modify these c + + 11 mistakes

**Comment by libornovax** [comment]
I am not sure what you are asking. For gcc you need to add `-std=c++11` flag to enable C++11. But try what I told you before

**Comment by zgq91** [comment]
@libornovax  thanks,  c++11 error has been resolved,The following error occurred while executing the command “ ./caffe/build/examples/ln/macc3d_pyramid_test caffe/models/macc3d/macc3d_0.3_r2_x2_to_x16_s2_deploy.prototxt  macc3d_0.3_r2_x2_to_x16_s2_iter_80000.caffemodel  image_list_test.txt detect.bb3txt  test.pgp
 ”
：

F1031 11:43:54.898808  1173 syncedmem.cpp:71] Check failed: error == cudaSuccess (2 vs. 0)  out of memory
*** Check failure stack trace: ***
    @     0x7f9c89c51daa  (unknown)
    @     0x7f9c89c51ce4  (unknown)
    @     0x7f9c89c516e6  (unknown)
    @     0x7f9c89c54687  (unknown)
    @     0x7f9c8a7fa790  caffe::SyncedMemory::mutable_gpu_data()
    @     0x7f9c8a7b5d12  caffe::Blob<>::mutable_gpu_data()
    @     0x7f9c8a77bd98  caffe::BaseConvolutionLayer<>::forward_gpu_gemm()
    @     0x7f9c8a834d02  caffe::ConvolutionLayer<>::Forward_gpu()
    @     0x7f9c8a644e4c  caffe::Net<>::ForwardFromTo()
    @     0x7f9c8a645245  caffe::Net<>::Forward()
    @           0x40c6ca  detectObjects()
    @           0x40d89d  runPyramidDetection()
    @           0x408e6c  main
    @     0x7f9c88195f45  (unknown)
    @           0x408f1c  (unknown)
    @              (nil)  (unknown)
Aborted (core dumped)

my  GPU memory:2G  ；model size is 60MB, GPU memory is not enough or other reasons

**Comment by libornovax** [comment]
The 60MB is just the size of the weights, when the network is built it consumes way more memory depending on the input image size. For example for a KITTI image it's about 3.5GB. If you want to run it on your GPU you need to split your input image into several crops.

**Comment by zgq91** [comment]
@libornovax my image_list_test.txt file: 
  1 /disk2/test/master_thesis_code/datasets/testing/image_2/000113.png

test.pgp file:
image_2/000113.png 721.537700 0.000000 609.559300 44.857280 0.000000 721.537700 172.854000 0.216379 0.000000 0.000000 1.000000 0.002746     0.000000 1.000000 0.000000 -2.100000

In the  macc3d_pyramid_test.cpp   program in the  detectObjects   function
// There are image projection matrices and ground planes - find the one for this image
         auto pgpi = pgps.find (path_image);

When the program is executed here will be wrong:
WARNING: PGP entry not found for image '/disk2/test/master_thesis_code/datasets/testing/image_2/000113.png'

But the path_image variable is just the path of the image.
Where did i set it wrong?

**Comment by libornovax** [comment]
This should be in the pgp file:

/disk2/test/master_thesis_code/datasets/testing/image_2/000113.png 721.537700 0.000000 609.559300 44.857280 0.000000 721.537700 172.854000 0.216379 0.000000 0.000000 1.000000 0.002746 0.000000 1.000000 0.000000 -2.100000

**Comment by zgq91** [comment]
@libornovax   The test.pgp file has been modified to: /disk2/test/master_thesis_code/datasets/testing/image_2/000113.png 721.537700 0.000000 609.559300 44.857280 0.000000 721.537700 172.854000 0.216379 0.000000 0.000000 1.000000 0.002746 0.000000 1.000000 0.000000 -2.100000   

But it is wrong:
Time net + bb extraction: 154 ms
Time to perform NMS: 0 ms
I1031 16:08:13.358901  1280 macc3d_pyramid_test.cpp:392] 
F1031 16:08:13.358922  1280 macc3d_pyramid_test.cpp:393] Check failed: boost::filesystem::exists(line) Image '' not found!
*** Check failure stack trace: ***
    @     0x7f3cd6fd15cd  google::LogMessage::Fail()
    @     0x7f3cd6fd3433  google::LogMessage::SendToLog()
    @     0x7f3cd6fd115b  google::LogMessage::Flush()
    @     0x7f3cd6fd3e1e  google::LogMessageFatal::~LogMessageFatal()
    @           0x410d0b  runPyramidDetection()
    @           0x409cab  main
    @     0x7f3cd5624830  __libc_start_main
    @           0x409d59  _start
    @              (nil)  (unknown)
Aborted (core dumped)

**Comment by libornovax** [comment]
That is because you have an empty line in the image_list.txt file. You should see an output file anyway...

**Comment by zgq91** [comment]
@libornovax   Thank you very much, demo running successfully, if I want to train kitti other objectives in the database, how should training

**Comment by libornovax** [comment]
You are welcome. For training you can modify the sample prototxt files in the `caffe/models` folder. Also check the Caffe website for instructions on training, I am not sure how experienced you are with that.

Note that the implementation currently supports detection of only one object category at a time and would have to be rewritten to support multiple.

**Comment by zgq91** [comment]
@libornovax  Can you share the code for your training, I only trained 2d object detection

**Comment by zgq91** [comment]
@libornovax  When training network how to kitti database 3d label into bb3txt format

**Comment by libornovax** [comment]
All the code you need for running the training is in the 'models' folder. Regarding the conversions, there are scripts for everything in the 'scripts/data' folder
