### ISSUE TITLE
.build_release/lib/libcaffe.so: undefined reference to `google::base::CheckOpMessageBuilder::NewString()'

### ISSUE THREAD

**Issue by JannaShen** [libornovax/master_thesis_code#47]
make caffe with ubuntu16.04 +gcc4.9 cuda8.0 ,get the error like below
CXX/LD -o .build_release/tools/upgrade_net_proto_text.bin
.build_release/lib/libcaffe.so: undefined reference to `google::base::CheckOpMessageBuilder::NewString()'
.build_release/lib/libcaffe.so: undefined reference to `leveldb::DB::Open(leveldb::Options const&, std::string const&, leveldb::DB**)'
.build_release/lib/libcaffe.so: undefined reference to `leveldb::Status::ToString() const'
collect2: error: ld returned 1 exit status
Makefile:625: recipe for target '.build_release/tools/upgrade_net_proto_text.bin' failed
make: *** [.build_release/tools/upgrade_net_proto_text.bin] Error 1

**Comment by libornovax** [comment]
Please check if you have all the necessary dependencies for Caffe and if they are built with gcc 4.9
