### ISSUE TITLE
Check failed: infile.is_open() BB3TXT file  could not be opened!

### ISSUE THREAD

**Issue by zgq91** [libornovax/master_thesis_code#48]
Hi:
   When I train the kitti database target is person, the following error occurred:

 Check failed: infile.is_open() BB3TXT file '/home/user/zhonggq/dataset/kitti/train_persion.bb3txt' could not be opened!

  train_persion.bb3txt  file  permissions 777

**Comment by libornovax** [comment]
Perhaps check your user rights or re-check the path. Please only post questions related to the code, this is obviously not.
