### ISSUE TITLE
inf error in result file: detections.bb3txt

### ISSUE THREAD

**Issue by PeiliangLi** [libornovax/master_thesis_code#52]
Hi, 
Thanks for your contribution. When I try to test the 3D detection on kitti datasets using your provided weight file, the output results are always inf:
![inf](https://user-images.githubusercontent.com/12999299/37018557-c69c5b1e-214f-11e8-88b1-9aa60f2d04ed.png)
And the detection time is very long(with using TITAN Xp):
![screenshot from 2018-03-06 15-05-51](https://user-images.githubusercontent.com/12999299/37018588-e771adbc-214f-11e8-981d-93731047be68.png)
Can you give some ideas about this result?

**Comment by libornovax** [comment]
Hi, interesting. I am not sure what could have gone wrong here, but try to check these:
  * I think the code only works with ~~CUDA 6~~ **CUDA 8 and CuDNN 5**
  * Do you use the code exactly as it is or you changed something?
  * The time is really long - is it really running on the GPU?
  * The long NMS time comes from the enormous amount of "valid" boxes with confidence > 0.1 - did you really load the weight file? The output seems quite random - there should not be INF in the box coordinates.
  * Is your PGP file correct? I.e. the numbers on the lines look like this: `image_2/005425.png 721.537700 0.000000 609.559300 44.857280 0.000000 721.537700 172.854000 0.216379 0.000000 0.000000 1.000000 0.002746 0.000000 1.000000 0.000000 -2.100000`

Let me know if any of that helped.

**Comment by PeiliangLi** [comment]
Thanks for your reply. I am using CUDA 8.0 and cudnn 4.0 now. I didn't change anything in the code and use the same PGP file as you provided except the image path. So do you think the only way is reinstall CUDA 6 on my computer?

**Comment by libornovax** [comment]
Sorry, I gave you wrong information! I use CUDA 8. However cudnn 5.1.3 - I would try updating cudnn to 5 as I recall there were some problems with it... (it does not work with cudnn 6)

**Comment by PeiliangLi** [comment]
Thanks, Libor, I will try cudnn 5.1.3, any update will be reported here.

**Comment by PeiliangLi** [comment]
I change to cudnn5, problem solved! thank you!
