### ISSUE TITLE
A question about inverse projecion 

### ISSUE THREAD

**Issue by JiangStein** [libornovax/master_thesis_code#53]
Dear Mr. Novak,
I am puzzled about how to get the image projection matrix P. In your thesis you mentioned that P=KR[I|-C], but then you said that C=-(KR)^(-1)p4, where p4 is the fourth column of P. How can I get C or p4?

`image_2/005425.png 721.537700 0.000000 609.559300 44.857280 0.000000 721.537700 172.854000 0.216379 0.000000 0.000000 1.000000 0.002746 0.000000 1.000000 0.000000 -2.100000`
How can I get p4(44.857820,0.216379,0.02746)? I simply set them to zero, and it is clear that there's something wrong with the result. Should p1~p3 be the camera intrinsics matrix？
Sincerely hoping for your reply. And I am sorry about my poor English T_T

![2018-05-21 14 47 30](https://user-images.githubusercontent.com/35327591/40293960-ec46ae7c-5d05-11e8-8753-4cc1852ca2d0.png)

**Comment by libornovax** [comment]
Hi @JiangStein, of course you either have to supply one or the other (C or p4). C is the camera center in world coordinates. p4 is just the 4th column of the projection matrix P, which you can compute as p4=-KRC, where K is a 3x3 matrix with intrinsic parameters (you can look here https://en.wikipedia.org/wiki/Camera_resectioning), R is a 3x3 rotation matrix.

That said p1~p3 is the KR part and p4 is -KRC.

If that does not help you can try posting the image and the line from the PGP file you are using and I can have a look into it.

**Comment by JiangStein** [comment]
Sorry for bothering you again after such a long time...I didn't try to solve this problem half a year ago because I only need to use the ground plane of the bounding box at that time, and it looks good enough.

I am now working for another project, and I hope to use your method again, but I still cannot solve that...

When I applied Intrinsic parameters(K) of my camera as P,  I got the result in the picture above. but when p1~p3 is the KR part and p4  is -KRC, It doesn't work...

I am puzzled about where should be the origin of world coordinates. Since I have restored the point cloud of the environment by using ORB-SLAM, I simply set the position of car in the first frame as the origin of world coordinates, and have successfully restored the overhead map of the environment, so I think there is nothing wrong with the camera position C and rotation matrix R.

![1778153134](https://user-images.githubusercontent.com/35327591/50285135-3a3a1000-0496-11e9-9323-f4ac6ba93fd4.png)
Here is an example of how I get K,C and R. The top-left one is the origin of camera matrix, the bottom-right one is the origin of world coordinate, where x is red, y is green, z is blue.

The size of my picture is 640x360 and I didn't resize it. the line from the PGP file is
```
/home/stein/dataset/parkingSlot/zed_0516_1700/resized/000000.png 
346.6559 0.000000 298.8324 0.000000 
0.000000 346.2212 186.4451 0.000000 
0.000000 0.000000 1.000000 0.000000 
0.000000 0.891600 0.452900 -1.52000
```
Through which I got the result shown in picture half a year ago. It is shown above.

The matrix K is
```
346.6559 0.000000 298.8324
0.000000 346.2212 186.4451
0.000000 0.000000 1.000000
```

The rotation matrix R from camera coordinates to world coordinates of this frame is
```
-1 0 0
0 0.4529 -0.8916
0 -0.8916 -0.4529
```
and I think the rotation matrix from world coordinates to camera coordinates is also R.

The camera position in world coordinates (matrix C) is
```
1 
-0.6 
1.52
```

However, after calculation by using  P=KR[I|-C], I got the result matrix P:
```
-346.6  -266.4  -135.3  392.5
     0      -9.43   -393.1 -591.9
     0   -0.8916 -0.4526 0.152
```
and it doesn't work.

I think the mistake I made might be:
1.I should crop the picture into KITTI size(1242x375) first.
2.I misunderstood K,R or C.
3.The unit of numbers is not the same(millimeter for matrix K, and meter for matrix R,C, ground plane.

Could you tell me what I did wrong?

Sincerely hoping for your reply.
