### ISSUE TITLE
difficulty in installation

### ISSUE THREAD

**Issue by drahmad89** [libornovax/master_thesis_code#56]
Hello,
I am using a linux OS. I am not experienced in C modules. I have tried to follow your instruction but many problems occurred in the process.
 I create PGP file ( you did not mention where it should be directed so i put it in the examples/ln)
I also create .txt file for the images name.
the command : ./caffe/build/examples/ln/macc3d_pyramid_test macc3d_0.3_r2_x2_to_x16_s2_deploy.prototxt macc3d_0.3_r2_x2_to_x16_s2_iter_80000.caffemodel image_list_test.txt detections.bb3txt test.pgp
is not working since build folder is remover. I tried it without build then i got problem with unknown command "macc3d_pyramid_test" I have add .cpp and stills not working.
I need to use your modules. Please help me

**Comment by libornovax** [comment]
Hi, when working with C/C++ you of course have to compile the code first, which creates the executables. In the case of this repository it means compiling Caffe. So if I consider you are in the root folder of this repo, you can do a series of commands like this:
```
cd caffe
mkdir build
cd build
cmake ..
make
```
Basically you create the build folder, then create Makefiles with Cmake and build the whole Caffe with `make`, which creates the executables in *build/examples*. Of course these steps will work only if you have Cmake. The building of this Caffe requires also OpenCV and depending on whether you want to use GPU or not also CUDA and CuDNN and other stuff.

That said, it will be probably quite hard for an inexperienced developer to compile Caffe (unless you have some magical setup of your machine), but I hope that will not discourage you. I recommend when in doubt try to search for how to compile Caffe, which should be basically the same.

I hope this helps!

**Comment by drahmad89** [comment]
thanks. I have installed all packages to compile ...
now when doing cmake .. , i am getting this error: 

  Syntax error in cmake code at

    /home/ahmad/master_thesis_code/caffe/examples/CMakeLists.txt:1

  when parsing string

    ${~/master_thesis_code/caffe/examples/*.cpp

  syntax error, unexpected cal_SYMBOL, expecting } (43)

**Comment by drahmad89** [comment]
Thanks i made some changes.

**Comment by LiuCKind** [comment]
> Thanks i made some changes.

hello~I am only an entry-level student in AI and I've been looking for some guidance in implementing this code. And I was wondering how to create .txt file for the images name and .pgp file?And I also met some problem in caffe compiling...can i get some help?Much appreciate!

**Comment by libornovax** [comment]
Hi, have a look around in the closed issues, perhaps you will find some responses there. Otherwise the file formats are described in the readme of this repo so that should be quite straightforward.
