### ISSUE TITLE
Files to be included for parsing arguments.

### ISSUE THREAD

**Issue by kabef94** [libornovax/master_thesis_code#58]
Hey.. I'm fairly new to python and I'm trying to run this code for a 3D box generation . During the parsing process can you please mention which are the files that need to be added as the parameters (I'm using Pycharm )? I couldn't figure out which files go where .
Please help me out .. Thanks !!

Input:
            path_detections:    **Path to the BB3TXT file with detections**
            detections_mapping: **Name of the mapping of the path_detections BB3TXT file**
            confidence:         Minimum confidence of a detection to be displayed
            path_gt:            **Path to the BB3TXT file with ground truth (optional)**
            gt_mapping:         **Name of the mapping of the path_gt BB3TXT file (optional)**
            path_datasets:      **Path to the "datasets" folder on this machine, replaces the path
                                that is in the BB3TXT files if provided**
            path_pgp:           **Path to the PGP file with image projection matrices and ground plane
                                equations**

Can you please tell me which files need to be included in the above paths?
Thanks

**Comment by libornovax** [comment]
Hi, I suppose you are trying to use the `show_bb3txt_detections.py`. So if you run in you command line
```
python show_bb3txt_detections.py --help
```
This will print help with the program options and how they are passed to the program. That should be quite clear I hope.
