### ISSUE TITLE
core dumped when try to run macc3d_pyramid_test.bin

### ISSUE THREAD

**Issue by sdimantsd** [libornovax/master_thesis_code#60]
Hi, 
First of all, thank you for you'r network!
when i'm try to run:
./caffe/build/examples/ln/macc3d_pyramid_test.bin ./caffe/models/macc3d/macc3d_0.3_r2_x2_to_x16_s2_deploy.prototxt macc3d_0.3_r2_x2_to_x16_s2_iter_80000.caffemodel image_list_test.txt detections.bb3txt pgpExample.pgp

i get that error msg:
...
...
..
I0116 10:18:31.926631 14095 net.cpp:747] Ignoring source layer loss_x16
I0116 10:18:31.941304 14095 macc3d_pyramid_test.cpp:387] mockup.png
F0116 10:18:51.745707 14095 syncedmem.hpp:33] Check failed: *ptr host allocation of size 29935616 failed
*** Check failure stack trace: ***
    @     0x7fb1d47750cd  google::LogMessage::Fail()
    @     0x7fb1d4776f33  google::LogMessage::SendToLog()
    @     0x7fb1d4774c28  google::LogMessage::Flush()
    @     0x7fb1d4777999  google::LogMessageFatal::~LogMessageFatal()
    @     0x7fb1d4c620e9  caffe::SyncedMemory::mutable_cpu_data()
    @     0x7fb1d4c6e102  caffe::Blob<>::mutable_cpu_data()
    @     0x7fb1d4bce67d  caffe::ConvolutionLayer<>::Forward_cpu()
    @     0x7fb1d4b1e220  caffe::Net<>::ForwardFromTo()
    @     0x7fb1d4b1e3f7  caffe::Net<>::Forward()
    @     0x55d406369664  (unknown)
    @     0x55d40636a931  (unknown)
    @     0x55d406362242  (unknown)
    @     0x7fb1cdafbb97  __libc_start_main
    @     0x55d4063622fa  (unknown)
Aborted (core dumped)

what can i do?

thx

**Comment by libornovax** [comment]
Hi, I would try to run it in some debugger. It looks like your computer is out of memory or something like that. If you run it in a debugger you should catch the error and see perhaps a better stack trace. This one does not really say much.

**Comment by sdimantsd** [comment]
Thanks! thanks!  thanks!  thanks!  thanks!
