### ISSUE TITLE
Projection matrix

### ISSUE THREAD

**Issue by anju000** [libornovax/master_thesis_code#61]
Please help me out as of how to give the projection matrix with my own data. I have collected checkerboard data and used opencv based functions to calibrate my camera. I cannot figure out exactly how you calculate the projection matrix. Can you please help..

**Comment by libornovax** [comment]
Obviously I will need some more information - saying "I don't know how to do it" without any details is not much of a question.

Anyway, in this issue https://github.com/libornovax/master_thesis_code/issues/59 it is quite well described how the projection matrix is calculated. You can also have look here https://en.wikipedia.org/wiki/Camera_resectioning, https://en.wikipedia.org/wiki/Camera_matrix
