### ISSUE TITLE
Questions for truncated objects

### ISSUE THREAD

**Issue by jkstyle2** [libornovax/master_thesis_code#62]
Thanks for sharing your great work! It's been very helpful understanding 3D detection.

One thing I'm wondering is how you deal with the truncated objects. 
In the video you uploaded, 
When our view gets close to other vehicles, truncation generally happens so that the 3D detector usually fails to detect, causing squashed 3D boxes. 
But in your detector, you seem to deal with it without squashing any boxes.
How have you done this issue? Can you share your idea?

**Comment by jkstyle2** [comment]
I just come up with an idea that if we don't train the network with truncated objects, then will i get a result like yours? or Will it cause another issue?

**Comment by libornovax** [comment]
Hi, you can see chapter 4.1.1 and 4.3.3 of the thesis - the 2D bounding boxes are extracted from the 3D ones and are not cropped to the image boundaries. Then you can use even the occluded and truncated objects in training.
