### ISSUE TITLE
Formula Derivation

### ISSUE THREAD

**Issue by Biyu-GitHub** [libornovax/master_thesis_code#63]
![微信截图_20191006131015](https://user-images.githubusercontent.com/37682385/66264587-afff4480-e83a-11e9-8d72-b18024e08900.png)
Thank you

**Comment by libornovax** [comment]
Hi, indeed it seems like there is an error, thank you for pointing it out! Sorry about that.

In the equation *l_x* should represent a direction vector *l_x = (KR)^-1 x*

**Comment by Biyu-GitHub** [comment]
thank you very much
